package com.avi.gharkhojo.Model

 data class Post(
    var ownerName:String?,
    var propertyType:String?,
    var preferredTenants:String?,
    var email:String? ,
    var tenantServed:String?,
    var phoneNumber:String? ,
    var builtUpArea:String? ,
    var floorPosition:String? ,
    var lockInPeriod:Int? ,
    var furnished:String? ,
    var noOfBedRoom:Int? ,
    var noOfBathroom:Int? ,
    var noOfBalcony:Int? ,
    var isAvailableDiningSpace:Boolean? ,
    var hasLift:Boolean? ,
    var hasSecurityGuard:Boolean? ,
    var hasParking:Boolean? ,
    var parkingCharge:Double? ,
    var rent:Double? ,
    var deposit:Double? ,
    var pincode:Int? ,
    var landMark:String? ,
    var houseNumber:Int? ,
    var area:String? ,
    var colony:String? ,
    var city:String? ,
    var state:String? ,
    var longitude:Double? ,
    var latitude:Double? ,
    var description:String? 
){
    constructor():this(null,null,
        null,null,
        null,null,
        null,null,
        null,null,
        null,null,
        null,null,
        null,null,
        null,
        null,null,
        null,null,
        null,null,
        null,null,
        null,null,
        null,null,null
        )
}